import React, { useMemo, useState } from 'react';
import './styles.css';

const runs = [
  { id: 'mica', name: 'Mica 7B', type: 'Mobile table wrap', status: 'Needs review', checks: '6 of 8 checks', time: '01:42', cost: '$0.03', date: 'Today, 10:24', detail: 'The last column moves below the table at 390px. Two labels are too small to read.' },
  { id: 'pine', name: 'Pine 3', type: 'Empty filter state', status: 'Passed', checks: '8 of 8 checks', time: '00:58', cost: '$0.01', date: 'Today, 09:51', detail: 'The empty state is clear, actionable, and keeps the filter context visible.' },
  { id: 'keyboard', name: 'Keyboard focus order', type: 'Keyboard focus order', status: 'Failed', checks: '4 of 8 checks', time: '02:13', cost: '$0.04', date: 'Yesterday, 16:08', detail: 'Focus skips the secondary action after opening the run details.' },
];

function App() {
  const [filter, setFilter] = useState('All runs');
  const [selected, setSelected] = useState('mica');
  const [preview, setPreview] = useState('normal');
  const filtered = useMemo(() => filter === 'All runs' ? runs : runs.filter(r => r.status === filter), [filter]);
  const current = runs.find(r => r.id === selected) || runs[0];
  const normal = () => setPreview('normal');
  const chooseFilter = e => { setFilter(e.target.value); if (e.target.value !== 'All runs' && selected === 'mica') setSelected('pine'); };
  return <div className="app-shell">
    <aside className="sidebar" aria-label="Primary navigation"><div className="brand"><span className="brand-mark">r</span><span>runbook</span></div><nav><a className="nav-item active" href="#runs"><span className="nav-icon">▦</span>Experiment runs <span className="count">3</span></a><a className="nav-item" href="#checks"><span className="nav-icon">✓</span>Checks</a><a className="nav-item" href="#settings"><span className="nav-icon">◌</span>Settings</a></nav><div className="sidebar-foot"><div className="workspace-dot">A</div><div><strong>Acme design</strong><small>Personal workspace</small></div><span className="chevron">⌄</span></div></aside>
    <main><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> Experiments</div><div className="top-actions"><button className="help" aria-label="Help">?</button><button className="avatar" aria-label="Account menu">JD</button></div></header><div className="content"><div className="page-heading"><div><p className="eyebrow">EXPERIMENTS / RUNS</p><h1>Experiment runs</h1><p className="summary">Small tests. Clear results.</p></div><button className="new-run">+ <span>New run</span></button></div>
      <section className="preview-tools" aria-label="Preview states"><span className="preview-label">Preview</span><button onClick={() => setPreview('empty')} className={preview === 'empty' ? 'tool active-tool' : 'tool'}>Empty state preview</button><button onClick={() => setPreview('loading')} className={preview === 'loading' ? 'tool active-tool' : 'tool'}>Loading preview</button><button onClick={() => setPreview('error')} className={preview === 'error' ? 'tool active-tool' : 'tool'}>Error preview</button></section>
      {preview === 'empty' && <div className="state-card"><div className="state-icon">⌕</div><h2>No runs match this filter</h2><p>Try changing the status filter to see more experiment runs.</p><button onClick={() => {setFilter('All runs'); normal()}} className="secondary">Clear filter</button></div>}
      {preview === 'loading' && <div className="state-card loading" role="status"><span className="spinner" aria-hidden="true"></span><h2>Loading runs…</h2><p>Fetching the latest experiment results.</p><button onClick={normal} className="secondary">Show normal state</button></div>}
      {preview === 'error' && <div className="state-card error" role="alert"><div className="state-icon">!</div><h2>Could not load experiment runs.</h2><p>Something went wrong while fetching this workspace.</p><button onClick={normal} className="secondary">Show normal state</button></div>}
      {preview === 'normal' && <><div className="controls"><label htmlFor="status">Status</label><select id="status" aria-label="Status" value={filter} onChange={chooseFilter}><option>All runs</option><option>Needs review</option><option>Passed</option><option>Failed</option></select><span className="result-count">{filtered.length} {filtered.length === 1 ? 'run' : 'runs'}</span></div><div className="run-layout"><section className="run-list" aria-label="Experiment runs list">{filtered.map(run => <button key={run.id} className={'run-row ' + (selected === run.id ? 'selected' : '')} aria-pressed={selected === run.id} onClick={() => setSelected(run.id)}><div className="run-main"><span className={'status-dot ' + run.status.toLowerCase().replace(' ', '-')}></span><div><strong>{run.name}</strong><span className="run-type">{run.type}</span></div></div><div className="run-status"><span className={'pill ' + run.status.toLowerCase().replace(' ', '-')}>{run.status}</span><span className="checks">{run.checks}</span></div><div className="run-meta"><span>{run.date}</span><span>{run.time}</span><span>{run.cost}</span></div><span className="row-arrow">›</span></button>)}</section><aside className="selected-panel" aria-label="Selected run"><div className="panel-kicker">SELECTED RUN</div><div className="panel-title"><div><h2>{current.name}</h2><p>{current.type}</p></div><span className={'pill ' + current.status.toLowerCase().replace(' ', '-')}>{current.status}</span></div><div className="note"><span className="note-mark">i</span><p>{current.detail}</p></div><div className="metrics"><div><span>Checks</span><strong>{current.checks}</strong></div><div><span>Runtime</span><strong>{current.time}</strong></div><div><span>Cost</span><strong>{current.cost}</strong></div></div><button aria-label="Inspect run" className="inspect">Inspect run <span>↗</span></button></aside></div></>}
    </div></main></div>;
}
export default App;
