import React, { useMemo, useState } from 'react';
import './styles.css';

const runs = [
  { id: 'R-024', name: 'Mobile table wrap', status: 'Needs review', model: 'Mica 7B', checks: '6 of 8 checks', time: 'Today, 10:24', duration: '01:42', cost: '$0.03', note: 'The last column moves below the table at 390px. Two labels are too small to read.', author: 'Nora Chen', branch: 'feat/mobile-table' },
  { id: 'R-023', name: 'Empty filter state', status: 'Passed', model: 'Pine 3', checks: '8 of 8 checks', time: 'Today, 09:51', duration: '00:58', cost: '$0.01', note: 'An empty search explains what happened and offers a clear path back to all runs.', author: 'Eli Morgan', branch: 'feat/empty-filters' },
  { id: 'R-022', name: 'Keyboard focus order', status: 'Failed', model: 'Mica 7B', checks: '4 of 8 checks', time: 'Yesterday, 16:08', duration: '02:13', cost: '$0.04', note: 'Focus skips the run summary after closing the details panel. Recheck the return target.', author: 'Sam Rivera', branch: 'fix/focus-return' },
];

export default function App() {
  const [status, setStatus] = useState('All runs');
  const [selectedId, setSelectedId] = useState('R-024');
  const [preview, setPreview] = useState('normal');
  const filtered = useMemo(() => runs.filter(run => status === 'All runs' || run.status === status), [status]);
  const selected = filtered.find(run => run.id === selectedId) || filtered[0];
  const normal = () => { setPreview('normal'); setStatus('All runs'); };
  return <div className="app-shell">
    <aside className="sidebar" aria-label="Workspace navigation"><a className="brand" href="#home" aria-label="Runbook home"><span className="brand-mark">r</span><span>runbook</span></a><div className="workspace"><span className="workspace-icon">N</span><span><b>Northstar</b><small>Product team</small></span><span className="chevron">⌄</span></div><div className="nav-label">WORKSPACE</div><nav className="nav-links" aria-label="Main navigation"><a href="#overview"><span className="nav-icon">▦</span>Overview</a><a href="#experiments" className="active" aria-current="page"><span className="nav-icon">◷</span>Experiment runs<span className="nav-count">3</span></a><a href="#projects"><span className="nav-icon">◇</span>Projects</a></nav><div className="sidebar-bottom"><div className="avatar">NC</div><div className="user-name"><b>Nora Chen</b><small>Team member</small></div><button className="more-button" aria-label="Account menu">···</button></div></aside>
    <main className="main-content"><header className="topbar"><div className="breadcrumbs"><span>Northstar</span><span className="crumb-slash">/</span><b>Experiment runs</b></div><div className="top-actions"><span className="sync"><i /> Synced just now</span><button className="help-button" aria-label="Help">?</button></div></header>
      <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow">RUNS <span>·</span> EXPERIMENTS</div><h1>Experiment runs</h1><p className="subtitle">Small tests. Clear results.</p></div><button className="new-run" onClick={() => setPreview('normal')}><span>＋</span> New experiment</button></div>
        <div className="summary-strip"><div className="summary-icon">◷</div><div><strong>Recent runs</strong><span>Review the latest results from your team.</span></div><span className="summary-date">LAST 7 DAYS</span></div>
        <section className="runs-section" aria-label="Experiment runs"><div className="list-toolbar"><div className="section-title"><h2>All experiments</h2><span className="count-pill">{filtered.length}</span></div><div className="filters"><label className="filter-label" htmlFor="status-filter">Status</label><select id="status-filter" aria-label="Status" value={status} onChange={e => { setStatus(e.target.value); setPreview('normal'); }}><option>All runs</option><option>Needs review</option><option>Passed</option><option>Failed</option></select><button className="filter-button" aria-label="Filter runs">☷ <span>Filter</span></button></div></div>
          {preview === 'loading' ? <div className="state-card" role="status"><span className="spinner" />Loading runs…<button onClick={normal}>Show normal state</button></div> : preview === 'error' ? <div className="state-card error-state" role="alert"><span className="error-mark">!</span><div><b>Could not load experiment runs.</b><p>Check your connection and try again.</p></div><button onClick={normal}>Show normal state</button></div> : preview === 'empty' || filtered.length === 0 ? <div className="empty-card"><div className="empty-symbol">⌕</div><h3>No runs match this filter</h3><p>Try another status, or clear the filter to see all experiment runs.</p><button className="clear-button" onClick={normal}>Clear filter</button></div> : <>
            <div className="run-list">{filtered.map(run => <button className={`run-row ${selected?.id === run.id ? 'selected' : ''}`} type="button" aria-pressed={selected?.id === run.id} key={run.id} onClick={() => setSelectedId(run.id)}><span className={`run-glyph ${run.status === 'Passed' ? 'pass' : run.status === 'Failed' ? 'fail' : 'review'}`}>{run.status === 'Passed' ? '✓' : run.status === 'Failed' ? '×' : '◷'}</span><span className="run-primary"><span className="run-name">{run.name}</span><span className="run-meta">{run.model}<span>·</span>{run.checks}<span>·</span>{run.duration} · {run.cost}</span></span><span className={`status-badge ${run.status.toLowerCase().replace(' ', '-')}`}><i />{run.status}</span><span className="run-date">{run.time}</span><span className="row-arrow">›</span></button>)}</div>
            {selected && <section className="detail-panel" aria-label="Selected run"><div className="detail-top"><div><div className="detail-kicker">SELECTED RUN <span>/{selected.id}</span></div><h3>{selected.name}</h3></div><button className="inspect-button" aria-label="Inspect run" onClick={() => setPreview('normal')}>Inspect run <span>↗</span></button></div><p className="run-note">{selected.note}</p><div className="detail-bottom"><div className="detail-metric"><span>MODEL</span><b>{selected.model}</b></div><div className="detail-metric"><span>CHECKS</span><b>{selected.checks}</b></div><div className="detail-metric"><span>DURATION</span><b>{selected.duration}</b></div><div className="detail-metric"><span>COST</span><b>{selected.cost}</b></div><div className="detail-by"><div className="mini-avatar">{selected.author.split(' ').map(s => s[0]).join('')}</div><span><b>{selected.author}</b><small>{selected.branch}</small></span></div></div></section>}
          </>}
        </section>
        <section className="previews" aria-label="Interface state previews"><div className="preview-copy"><span className="preview-dot" /><div><b>State previews</b><p>Review how the run list responds to common states.</p></div></div><div className="preview-actions"><button onClick={() => { setPreview('empty'); setStatus('All runs'); }}><span className="preview-icon">⌕</span>Empty state preview <span className="small-arrow">↗</span></button><button onClick={() => { setPreview('loading'); setStatus('All runs'); }}><span className="preview-icon">◌</span>Loading preview <span className="small-arrow">↗</span></button><button onClick={() => { setPreview('error'); setStatus('All runs'); }}><span className="preview-icon">!</span>Error preview <span className="small-arrow">↗</span></button></div></section><footer className="page-footer"><span>Showing {filtered.length} of 3 runs</span><span>Runbook <b>·</b> Experiments are team-visible</span></footer>
      </div>
    </main>
  </div>;
}
